# Generated by Django 5.0 on 2024-02-17 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialNetwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='shared_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialNetwork.invitation'),
        ),
        migrations.AlterField(
            model_name='post',
            name='shared_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialNetwork.post'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='shared_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialNetwork.survey'),
        ),
    ]
